project:
  type: website
  output-dir: docs

website:
  title: "tof1-2425"
  repo-url: https://github.com/lektorodd/tof1-2425
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



